# Generated by Django 5.2.8 on 2025-11-30 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TextDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("macro_f1_score", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("validation_file_path", models.CharField(blank=True, max_length=500)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_results",
                        to="analyzer.textdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TextEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("original_text", models.TextField(blank=True)),
                ("normalized_text", models.TextField(blank=True)),
                (
                    "sentiment_score",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Нейтральная"),
                            (1, "Положительная"),
                            (2, "Отрицательная"),
                        ],
                        null=True,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_manually_corrected", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="analyzer.textdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "sentiment_score"],
                        name="analyzer_te_documen_ae0bc2_idx",
                    ),
                    models.Index(
                        fields=["source"], name="analyzer_te_source_ebe396_idx"
                    ),
                ],
            },
        ),
    ]
